services:
  # dind for jenkins
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    ports:
      - "2376:2376"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-certs-ca:/certs/ca
      - jenkins-data:/var/jenkins_home
      - dind-lib:/var/lib/docker
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true

# The above is equivalent to 
# docker run 
#   --name jenkins-dind 
#   --network jenkins 
#   --network alias
#   --env DOCKER_TLS_CERTDIR=/certs
#   --volume jenkins-docker-certs:/certs/client
#   --volume jenkins-certs-ca:/certs/ca
#   --volume jenkins-data:/var/jenkins_home
#   --publish 2376:2376
#   --privileged
#   docker:dind

  # jenkins service 
  jenkins-blueocean:
    container_name: jenkins-blueocean
    build: 
      dockerfile: jenkinsDinD.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    depends_on:
      - jenkins-docker

volumes:
  jenkins-docker-certs:
  jenkins-certs-ca:
  jenkins-data:
  dind-lib:

networks:
  jenkins:
    external: true 
  # when network already has been created, add external: true

# use "--storage-driver overlay2" if linux or macOS
